### ISSUE TITLE
[Bug] QueryParam Types are not validated correctly

### ISSUE THREAD

**Issue by nikolaischunk** [BirthdayyBot/BirthdayyBot#121]
### Issue
When registering a birthday, there is a error message, saying that the parameter types are not correct.
This Bug was introduced when refactoring the APIs.
![grafik](https://user-images.githubusercontent.com/58025175/226564928-2193e4d8-3684-4c71-be91-101d702cb458.png)
### Possible solutions:
- Switch to `any` instead of `string` type
- Pass the parameters in the body not the url parameter.

**Comment by Swiizyy** [comment]
Use of `zod` to validate data, planned
