### ISSUE TITLE
[Enhancement] Extract the custom bot deployment configs to a private repository

### ISSUE THREAD

**Issue by nikolaischunk** [BirthdayyBot/BirthdayyBot#412]
## Current Status
Currently we have all custom bot deployment information in the `continuous-delivery.yml` action file in this repostory.
This exposes information to the public, that would be better if it is privated.
Also the changes in the file need to be merged to testing and production every time.

## Solution
- Extract the contents of the custom bot
- Put them into a seperate private repository
- Use the following [action ](https://github.com/peter-evans/repository-dispatch)to trigger this external workflow from here.

**Comment by Swiizyy** [comment]
This will be solved with "Portainer".
